### ISSUE TITLE
Error with panda3d 1.10

### ISSUE THREAD

**Issue by artygrand** [fireclawthefox/panda3d-tutorial#1]
Thank you for this tutorial! It really helps.
Looks like some api changed in 1.10 so I have error
```
File "...\P3D Tutorial\game\player.py", line 44, in __init__
    self.leftButton = KeyboardButton.asciiKey("d")
TypeError: ascii_key() argument must be a byte string of length 1, not str
```

**Comment by rdb** [comment]
Is this in Python 3 or Python 2? The error seems to say it is expecting `asciiKey(b"d")`, but this could be an issue in your version of Panda rather than an issue with the book.

I think that in recent versions of Panda, this will work too:
```
self.leftButton = "d"
```

**Comment by artygrand** [comment]
3.6

PyCharm says that Expected type 'KeyboardButton', got str instead

**Comment by fireclawthefox** [comment]
that sounds like a python 2 vs 3 version problem. I've started converting the samples in the tutorial to python 3 as well as p3d version 1.10 but it will take some more time until it's done. I think adding doing KeyboardButton.asciiKey(b"d") might work (that's not tested yet)

**Comment by artygrand** [comment]
works nice. Thanks again
