### ISSUE TITLE
I have some small questions

### ISSUE THREAD

**Issue by tjnu1430130310** [fireclawthefox/panda3d-tutorial#3]
Hello, I am so sorry, please forgive me for my bad English.

In the User interactions of Chapter 3: Develop on page 39 of the tutorial, “Having done that, you should be able to move the character left and right with the 'A' and 'D' keys on your keyboard if you restart the application.”

Is the 'A' and 'D' is 'D' and 'F'?

I followed your tutorial and built new folders and new files. After creating a single role, I have been reporting an error. . . Say I didn't define the global variable 'loader':

Traceback (most recent call last):
  File "main.py", line 10, in <module>
    app = Main()
  File "main.py", line 7, in __init__
    self.player = Player(0, 1)
  File "D:\documents\Panda3D\code\game\player.py", line 33, in __init__
    "defend":charPath + "defend"
  File "C:\Anaconda3\envs\py2\lib\site-packages\direct\actor\Actor.py", line 280, in __init__
    self.loadModel(models, copy = copy, okMissing = okMissing)
  File "C:\Anaconda3\envs\py2\lib\site-packages\direct\actor\Actor.py", line 1910, in loadModel
    model = loader.loadModel(modelPath, loaderOptions = loaderOptions, okMissing = okMissing)
NameError: global name 'loader' is not defined

After joining the second role, the error is like this:

Traceback (most recent call last):
  File "main.py", line 23, in <module>
    app = Main()
  File "main.py", line 12, in __init__
    self.player = Player(1, "p1")
TypeError: __init__() takes exactly 4 arguments (3 given)

I changed

self.player = Player(1, "p1")

self.player2 = Player(1, "p2")

to

self.player = Player(1, "p1", 1)

self.player2 = Player(1, "p2", 2)

Later, it is again the fault of the definition of the loader:

Traceback (most recent call last):
  File "main.py", line 23, in <module>
    app = Main()
  File "main.py", line 12, in __init__
    self.player = Player(1, "p1", 1)
  File "D:\documents\Panda3D\code\game\player.py", line 32, in __init__
    "defend":charPath + "defend"
  File "C:\Anaconda3\envs\py2\lib\site-packages\direct\actor\Actor.py", line 280, in __init__
    self.loadModel(models, copy = copy, okMissing = okMissing)
  File "C:\Anaconda3\envs\py2\lib\site-packages\direct\actor\Actor.py", line 1910, in loadModel
    model = loader.loadModel(modelPath, loaderOptions = loaderOptions, okMissing = okMissing)
NameError: global name 'loader' is not defined

Maybe I didn't understand it. After all, my English is too bad. I am so sorry to bother you.

Thank you so much for your tutorial.

**Comment by fireclawthefox** [comment]
Thanks for the hints I will fix these parts asap.

The letter A is definitely wrong in that sentence and has to be F as you
correctly noted.

As for the Player class call it should be
Player(1,1,"p1") and Player(2,2,"p2")

This might also fix the loader problem as loader should be available after
the call to ShowBase.__init__(self) in the Main class. If not, might you be
able to upload your current code somewhere so I can take a look at it?

Leaf L Libra <notifications@github.com> schrieb am Fr., 20. Juli 2018,
13:05:

**Comment by tjnu1430130310** [comment]
Hello. My code upload to

https://github.com/tjnu1430130310/panda3d-tutorial-code

Now it’s like this :
![image](https://user-images.githubusercontent.com/20507237/43029509-6aebac86-8cb9-11e8-8d9f-27cfa98f3463.png)
a gray canvas

Thank you very much, I found the object, so happy. \(^o^)/

**Comment by fireclawthefox** [comment]
Great.
So far everything looks good with your code and if you simply add `app.enterGame()` right after `app = Main()` you should already be able to see and control the characters.
Will close this issue now.

**Comment by tjnu1430130310** [comment]
Perfect, thanks~
